package com.dolos.alert.domain;

import jakarta.persistence.AttributeConverter;
import jakarta.persistence.Converter;
import java.util.List;

/**
 * Persists the {@code reasons} list as a single newline-delimited TEXT column. Reasons are
 * generated by scoring as single-line strings, so newline is a safe, collision-free delimiter and
 * avoids a child table for what is naturally a small value list on the alert row.
 */
@Converter
public class AlertReasonsConverter implements AttributeConverter<List<String>, String> {

    private static final String DELIMITER = "\n";

    @Override
    public String convertToDatabaseColumn(List<String> attribute) {
        return attribute == null || attribute.isEmpty() ? "" : String.join(DELIMITER, attribute);
    }

    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        return dbData == null || dbData.isBlank() ? List.of() : List.of(dbData.split(DELIMITER));
    }
}
